---
applications:
- name: find-data-beta
  instances: 4
  memory: 512M
  buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.34
  routes:
  - route: find-data-beta.cloudapps.digital
  - route: data.gov.uk
  env:
    RAILS_ENV: production
    RACK_ENV: production
    CKAN_REDIRECTION_URL: ckan.publishing.service.gov.uk
  services:
  - find-production-secrets
  - logit-ssl-drain
  - elasticsearch-beta-production
