---
applications:
- name: find-data-beta
  memory: 256M
  buildpack: ruby_buildpack
  routes:
  - route: find-data-beta.cloudapps.digital
  - route: beta.data.gov.uk
  env:
    RAILS_ENV: production
    RACK_ENV: production
  services:
  - find-production-secrets
  - logit-ssl-drain
  - beta-production-elasticsearch
