default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: find_data_beta_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: find_data_beta_test
  url: <%= ENV['DATABASE_URL'] %>
