default: &default
  host: http://localhost:9200
  transport_options:
    request:
      timeout: 5

test:
  <<: *default

staging: &default
  <<: *default
  host: <%= ENV['ES_HOST'] %>

production: &default
  <<: *default
  host: <%= ENV['ES_HOST'] %>
