test:
  username: 'test-user@mail.com'
  password: 'password123'
  api_key: '123abc'
  end_point: 'https://test_zendesk_url.com/api/v2'

production:
  vcap_services: '<%= ENV["VCAP_SERVICES"] %>'

#In both staging and development environments zendesk ticket sending is not enabled
