test:
  username: 'test-user@mail.com'
  password: 'your-fake-zendesk-password-here'
  api_key: '123abc'
  end_point: 'https://test_zendesk_url.com/api/v2'

production:
  vcap_services: '<%= ENV["VCAP_SERVICES"] %>'

# In both staging and development environments zendesk ticket sending is not enabled.
# To enable, uncomment the following and amend config/initializers/zendesk.rb accordingly

development:
#   username: <%= ENV["ZENDESK_USERNAME"] %>
#   password: <%= ENV["ZENDESK_PASSWORD"] %>
#   api key: <%= ENV["ZENDESK_API_KEY"] %>
#   end_point: <%= ENV["ZENDESK_END_POINT"] %>

staging:
#   vcap_services: '<%= ENV["VCAP_SERVICES"] %>'
